version: '3'

services:

  blog:
    image: &blog_version blog:0.0.1
    build:
      context: blog
      dockerfile: Dockerfile
    environment:
      PORT: 5346
      BL_VERSION: *blog_version
      POSTGRES_USER: blog_fast
      POSTGRES_PASSWORD: blog_fast
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 7567
      POSTGRES_DB: blog_fast
    ports:
      - "5346:5346"
    volumes:
      - ./blog:/home/blog
    working_dir: /home/blog
    command: gunicorn -b :5346 -k uvicorn.workers.UvicornWorker blog.main:app

  ### DATABASE
  postgres:
    image: postgres:12.4
    # Uncomment to have data saved if you stop the image
    # volumes:
      # - postgres_data:/var/lib/postgresql/data/
    ports:
      - "7567:7567"
    environment:
      - POSTGRES_DB=blog_fast
      - POSTGRES_USER=blog_fast
      - POSTGRES_PASSWORD=blog_fast
    command: -p 7567

# Uncomment to have data saved if you stop the image
# volumes:
  # postgres_data:
