version: '3'

services:

  blog:
    image: &blog_version blog:0.0.1
    build:
      context: blog
      dockerfile: Dockerfile
    environment:
      PORT: 4999
      BL_VERSION: *blog_version
    ports:
      - "4999:4999"
    volumes:
      - ./blog:/home/blog
    working_dir: /home/blog
